package com.tcc.ecoplus.ecorecicla.model.entity;

public enum Permission {

    ADMIN_READ("ADMIN_READ"),
    ADMIN_UPDATE("ADMIN_UPDATE"),
    ADMIN_CREATE("ADMIN_CREATE"),
    ADMIN_DELETE("ADMIN_DELETE"),

    REPRESENTANTECOLETORA_READ("REPRESENTANTECOLETORA_READ"),
    REPRESENTANTECOLETORA_UPDATE("REPRESENTANTECOLETORA_UPDATE"),
    REPRESENTANTECOLETORA_CREATE("REPRESENTANTECOLETORA_CREATE"),
    REPRESENTANTECOLETORA_DELETE("REPRESENTANTECOLETORA_DELETE"),

    REPRESENTANTEDESTINADORA_READ("REPRESENTANTEDESTINADORA_READ"),
    REPRESENTANTEDESTINADORA_UPDATE("REPRESENTANTEDESTINADORA_UPDATE"),
    REPRESENTANTEDESTINADORA_CREATE("REPRESENTANTEDESTINADORA_CREATE"),
    REPRESENTANTEDESTINADORA_DELETE("REPRESENTANTEDESTINADORA_DELETE");

    private final String permission;

    Permission(String permission) {
        this.permission = permission;
    }

    public String getPermission() {
        return permission;
    }
}
